server:
  port: 9001
  context-path: /

spring:
  application:
    name: scloud-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config
        git:
          uri: https://github.com/peerlesszh/scloud-config-repo.git
      discovery:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka/
