server:
  port: 9001
  context-path: /

spring:
  application:
    name: scloud-config-server
  profiles:
    active: local
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config
      discovery:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka/
